In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## CLEAN

In [2]:
import pandas as pd
path = "/content/drive/MyDrive/DV_videogames/games_march2025.csv"

df = pd.read_csv(path)
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89618 entries, 0 to 89617
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   appid                     89618 non-null  int64
 1   name                      89618 non-null  object
 2   release_date              89618 non-null  object
 3   required_age              89618 non-null  int64
 4   price                     89618 non-null  float64
 5   dlc_count                 89618 non-null  int64
 6   detailed_description      89421 non-null  object
 7   about_the_game            89398 non-null  object
 8   short_description         89498 non-null  object
 9   reviews                   10401 non-null  object
 10  header_image              89618 non-null  object
 11  website                   41114 non-null  object
 12  support_url               44110 non-null  object
 13  support_email             78798 non-null  object
 14  windows                   89618 non-null  bool
 15  mac                       89618 non-null  bool
 16  linux                     89618 non-null  bool
 17  metacritic_score          89618 non-null  int64
 18  metacritic_url            3547 non-null   object
 19  achievements              89618 non-null  int64
 20  recommendations           89618 non-null  int64
 21  notes                     16643 non-null  object
 22  supported_languages       89618 non-null  object
 23  full_audio_languages      89618 non-null  object
 24  packages                  89618 non-null  object
 25  developers                89618 non-null  object
 26  publishers                89618 non-null  object
 27  categories                89618 non-null  object
 28  genres                    89618 non-null  object
 29  screenshots               89618 non-null  object
 30  movies                    89618 non-null  object
 31  user_score                89618 non-null  int64
 32  score_rank                39 non-null     float64
 33  positive                  89618 non-null  int64
 34  negative                  89618 non-null  int64
 35  estimated_owners          89618 non-null  object
 36  average_playtime_forever  89618 non-null  int64
 37  average_playtime_2weeks   89618 non-null  int64
 38  median_playtime_forever   89618 non-null  int64
 39  median_playtime_2weeks    89618 non-null  int64
 40  discount                  89618 non-null  int64
 41  peak_ccu                  89618 non-null  int64
 42  tags                      89618 non-null  object
 43  pct_pos_total             89618 non-null  int64
 44  num_reviews_total         89618 non-null  int64
 45  pct_pos_recent            89618 non-null  int64
 46  num_reviews_recent        89618 non-null  int64
dtypes: bool(3), float64(2), int64(19), object(23)
memory usage: 30.3+ MB

,appid,required_age,price,dlc_count,metacritic_score,achievements,recommendations,user_score,score_rank,positive,...,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
count,8.961800e+04,89618.000000,89618.000000,89618.000000,89618.000000,89618.000000,8.961800e+04,89618.000000,39.000000,8.961800e+04,...,8.961800e+04,89618.000000,8.961800e+04,89618.000000,89618.000000,8.961800e+04,89618.000000,8.961800e+04,89618.000000,89618.000000
mean,1.656904e+06,0.183624,7.309623,0.595583,2.903245,20.552333,1.009401e+03,0.032817,99.128205,1.269896e+03,...,1.149119e+02,5.032694,1.147559e+02,5.301814,4.558627,9.833994e+01,45.352418,1.315490e+03,5.231639,15.584581
std,9.168390e+05,1.725594,13.331073,15.351920,14.445358,163.562418,2.204815e+04,1.615149,0.695076,3.181441e+04,...,6.814748e+03,181.100334,8.806711e+03,189.591095,16.538036,5.717544e+03,40.685695,3.542370e+04,22.335358,444.277307
min,2.000000e+01,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,98.000000,0.000000e+00,...,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,-1.000000,-1.000000e+00,-1.000000,-1.000000
25%,8.550525e+05,0.000000,0.990000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,99.000000,1.000000e+00,...,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,-1.000000,-1.000000e+00,-1.000000,-1.000000
50%,1.524730e+06,0.000000,4.990000,0.000000,0.000000,5.000000,0.000000e+00,0.000000,99.000000,1.000000e+01,...,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,60.000000,1.500000e+01,-1.000000,-1.000000
75%,2.430852e+06,0.000000,9.990000,0.000000,0.000000,20.000000,0.000000e+00,0.000000,100.000000,5.800000e+01,...,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,84.000000,8.100000e+01,-1.000000,-1.000000
max,3.542350e+06,21.000000,999.980000,3427.000000,97.000000,9821.000000,4.401572e+06,100.000000,100.000000,7.480813e+06,...,1.462997e+06,18568.000000,1.462997e+06,18568.000000,100.000000,1.212356e+06,100.000000,8.632939e+06,100.000000,96473.000000

Release Year

In [3]:
# Conversione release_date in datetime
df["release_date_parsed"] = pd.to_datetime(
    df["release_date"],
    errors="coerce"
)

# Estrazione anno
df["release_year"] = df["release_date_parsed"].dt.year

# Controlli base
df[["release_date", "release_date_parsed", "release_year"]].head(10)

  release_date release_date_parsed  release_year
0   2012-08-21          2012-08-21          2012
1   2017-12-21          2017-12-21          2017
2   2013-07-09          2013-07-09          2013
3   2015-04-13          2015-04-13          2015
4   2015-12-01          2015-12-01          2015
5   2007-10-10          2007-10-10          2007
6   2011-05-16          2011-05-16          2011
7   2018-02-08          2018-02-08          2018
8   2006-11-29          2006-11-29          2006
9   2020-11-04          2020-11-04          2020

In [4]:
# Quanti valori non convertiti?
df["release_year"].isna().sum()

# Distribuzione per anno
df["release_year"].value_counts().sort_index().head(10), \
df["release_year"].value_counts().sort_index().tail(10)

(release_year
 1997    2
 1999    1
 2001    2
 2002    1
 2003    2
 2004    2
 2005    4
 2006    9
 2007    8
 2008    7
 Name: count, dtype: int64,
 release_year
 2016     4160
 2017     5967
 2018     7443
 2019     6146
 2020     8568
 2021     8294
 2022     9158
 2023    12735
 2024    18282
 2025     3573
 Name: count, dtype: int64)

Colonne

In [5]:
# Selezione colonne
cols_s2 = [
    "appid",
    "name",
    "release_date",
    "price",
    "dlc_count",
    "discount",
    "required_age",
    "categories",
    "genres",
    "tags",
    "positive",
    "negative",
    "num_reviews_total",
    "pct_pos_total",
    "peak_ccu",
    "average_playtime_forever",
    "median_playtime_forever",
    "average_playtime_2weeks",
    "median_playtime_2weeks",
    "estimated_owners",
    "pct_pos_recent",
    "num_reviews_recent",
    "achievements",
]

# 2) controllo colonne mancanti
missing = [c for c in cols_s2 if c not in df.columns]
extra_present = [c for c in df.columns if c in cols_s2]

print("Requested columns:", len(cols_s2))
print("Found columns:", len(extra_present))

if missing:
    print("\n Missing columns (NOT found in df):")
    for c in missing:
        print("-", c)

print("\n Preview of selected columns (first 5 rows):")
df_s2 = df[cols_s2].copy()
display(df_s2.head())
print("\nShape:", df_s2.shape)

Requested columns: 23
Found columns: 23

 Preview of selected columns (first 5 rows):

,appid,name,release_date,price,dlc_count,discount,required_age,categories,genres,tags,...,pct_pos_total,peak_ccu,average_playtime_forever,median_playtime_forever,average_playtime_2weeks,median_playtime_2weeks,estimated_owners,pct_pos_recent,num_reviews_recent,achievements
0,730,Counter-Strike 2,2012-08-21,0.00,1,0,0,"['Multi-player', 'Cross-Platform Multiplayer',...","['Action', 'Free To Play']","{'FPS': 90857, 'Shooter': 65397, 'Multiplayer'...",...,86,1212356,33189,5174,879,350,100000000 - 200000000,82,96473,1
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0.00,0,0,0,"['Multi-player', 'PvP', 'Online PvP', 'Stats',...","['Action', 'Adventure', 'Massively Multiplayer...","{'Survival': 14838, 'Shooter': 12727, 'Battle ...",...,59,616738,0,0,0,0,50000000 - 100000000,68,16720,37
2,570,Dota 2,2013-07-09,0.00,2,0,0,"['Multi-player', 'Co-op', 'Steam Trading Cards...","['Action', 'Strategy', 'Free To Play']","{'Free to Play': 59933, 'MOBA': 20158, 'Multip...",...,81,555977,43031,898,1536,892,200000000 - 500000000,80,29366,0
3,271590,Grand Theft Auto V Legacy,2015-04-13,0.00,0,0,17,"['Single-player', 'Multi-player', 'PvP', 'Onli...","['Action', 'Adventure']","{'Open World': 32644, 'Action': 23539, 'Multip...",...,87,117698,19323,7101,771,74,50000000 - 100000000,92,17517,77
4,359550,Tom Clancy's Rainbow Six® Siege,2015-12-01,3.99,9,80,17,"['Single-player', 'Multi-player', 'PvP', 'Onli...",['Action'],"{'FPS': 9831, 'PvP': 9162, 'e-sports': 9072, '...",...,84,89916,14204,2434,682,306,20000000 - 50000000,76,12608,0

Shape: (89618, 23)

Trattare gli zero

In [6]:
# Percentuale di zeri per colonna (escludendo price)
zero_ratio = (
    (df_s2 == 0).sum() / len(df_s2)
).sort_values(ascending=False)

zero_ratio

average_playtime_2weeks     0.991999
median_playtime_2weeks      0.991999
required_age                0.988518
discount                    0.916825
average_playtime_forever    0.910621
median_playtime_forever     0.910621
dlc_count                   0.841215
peak_ccu                    0.788882
achievements                0.458502
negative                    0.339173
positive                    0.216753
price                       0.158004
pct_pos_total               0.000201
pct_pos_recent              0.000022
release_date                0.000000
name                        0.000000
appid                       0.000000
genres                      0.000000
tags                        0.000000
num_reviews_total           0.000000
categories                  0.000000
estimated_owners            0.000000
num_reviews_recent          0.000000
dtype: float64

In [7]:
df_s2[
    [
        "average_playtime_forever",
        "median_playtime_forever",
        "average_playtime_2weeks",
        "median_playtime_2weeks",
        "pct_pos_recent",
        "num_reviews_recent",
        "peak_ccu",
        "achievements",
    ]
].describe()

,average_playtime_forever,median_playtime_forever,average_playtime_2weeks,median_playtime_2weeks,pct_pos_recent,num_reviews_recent,peak_ccu,achievements
count,8.961800e+04,8.961800e+04,89618.000000,89618.000000,89618.000000,89618.000000,8.961800e+04,89618.000000
mean,1.149119e+02,1.147559e+02,5.032694,5.301814,5.231639,15.584581,9.833994e+01,20.552333
std,6.814748e+03,8.806711e+03,181.100334,189.591095,22.335358,444.277307,5.717544e+03,163.562418
min,0.000000e+00,0.000000e+00,0.000000,0.000000,-1.000000,-1.000000,0.000000e+00,0.000000
25%,0.000000e+00,0.000000e+00,0.000000,0.000000,-1.000000,-1.000000,0.000000e+00,0.000000
50%,0.000000e+00,0.000000e+00,0.000000,0.000000,-1.000000,-1.000000,0.000000e+00,5.000000
75%,0.000000e+00,0.000000e+00,0.000000,0.000000,-1.000000,-1.000000,0.000000e+00,20.000000
max,1.462997e+06,1.462997e+06,18568.000000,18568.000000,100.000000,96473.000000,1.212356e+06,9821.000000

Colonne numeriche

In [8]:
# colonne numeriche come numeric
num_cols = [
    "price",
    "dlc_count",
    "discount",
    "required_age",
    "positive",
    "negative",
    "num_reviews_total",
    "pct_pos_total",
    "peak_ccu",
    "average_playtime_forever",
    "median_playtime_forever",
    "average_playtime_2weeks",
    "median_playtime_2weeks",
    "pct_pos_recent",
    "num_reviews_recent",
    "achievements",
]

# converte a numeric
for c in num_cols:
    df_s2[c] = pd.to_numeric(df_s2[c], errors="coerce")

print("\nMissing values (numeric cols):")
print(df_s2[num_cols].isna().sum().sort_values(ascending=False).head(15))

Missing values (numeric cols):
price                       0
dlc_count                   0
discount                    0
required_age                0
positive                    0
negative                    0
num_reviews_total           0
pct_pos_total               0
peak_ccu                    0
average_playtime_forever    0
median_playtime_forever     0
average_playtime_2weeks     0
median_playtime_2weeks      0
pct_pos_recent              0
num_reviews_recent          0
dtype: int64

Estimated Owners

In [9]:
# split del range "low - high"
owners_split = (
    df_s2["estimated_owners"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.split(r"\s*-\s*", expand=True)
)

df_s2["owners_low"] = pd.to_numeric(owners_split[0], errors="coerce")
df_s2["owners_high"] = pd.to_numeric(owners_split[1], errors="coerce")

# midpoint (proxy continuo)
df_s2["owners_mid"] = (df_s2["owners_low"] + df_s2["owners_high"]) / 2

# 3) tier categorici
def owners_tier(x):
    if pd.isna(x):
        return "Unknown"
    elif x < 20_000:
        return "≤20k"
    elif x < 200_000:
        return "20k–200k"
    elif x < 2_000_000:
        return "200k–2M"
    elif x < 20_000_000:
        return "2M–20M"
    elif x < 50_000_000:
        return "20M–50M"
    elif x < 100_000_000:
        return "50M–100M"
    elif x < 200_000_000:
        return "100M–200M"
    else:
        return "200M+"

df_s2["owners_tier"] = df_s2["owners_mid"].apply(owners_tier)


print("Owners parsing check:")
print(df_s2[["estimated_owners", "owners_low", "owners_high", "owners_mid", "owners_tier"]].head(10))

print("\nOwners tier distribution:")
print(df_s2["owners_tier"].value_counts())

Owners parsing check:
        estimated_owners  owners_low  owners_high   owners_mid owners_tier
0  100000000 - 200000000   100000000    200000000  150000000.0   100M–200M
1   50000000 - 100000000    50000000    100000000   75000000.0    50M–100M
2  200000000 - 500000000   200000000    500000000  350000000.0       200M+
3   50000000 - 100000000    50000000    100000000   75000000.0    50M–100M
4    20000000 - 50000000    20000000     50000000   35000000.0     20M–50M
5    20000000 - 50000000    20000000     50000000   35000000.0     20M–50M
6    20000000 - 50000000    20000000     50000000   35000000.0     20M–50M
7    20000000 - 50000000    20000000     50000000   35000000.0     20M–50M
8    20000000 - 50000000    20000000     50000000   35000000.0     20M–50M
9   50000000 - 100000000    50000000    100000000   75000000.0    50M–100M

Owners tier distribution:
owners_tier
≤20k         67738
20k–200k     17240
200k–2M       4081
2M–20M         523
20M–50M         24
50M–100M        10
200M+            1
100M–200M        1
Name: count, dtype: int64

In [10]:

df_s2[["owners_mid", "num_reviews_total", "peak_ccu"]].describe()

         owners_mid  num_reviews_total      peak_ccu
count  8.961800e+04       8.961800e+04  8.961800e+04
mean   1.011338e+05       1.315490e+03  9.833994e+01
std    1.677279e+06       3.542370e+04  5.717544e+03
min    0.000000e+00      -1.000000e+00  0.000000e+00
25%    1.000000e+04      -1.000000e+00  0.000000e+00
50%    1.000000e+04       1.500000e+01  0.000000e+00
75%    1.000000e+04       8.100000e+01  0.000000e+00
max    3.500000e+08       8.632939e+06  1.212356e+06

In [11]:
# Correlazioni semplici
df_s2[["owners_mid", "num_reviews_total", "peak_ccu"]].corr()

                   owners_mid  num_reviews_total  peak_ccu
owners_mid           1.000000           0.681564  0.599933
num_reviews_total    0.681564           1.000000  0.831114
peak_ccu             0.599933           0.831114  1.000000

In [12]:
# es
df_s2.sort_values("owners_mid", ascending=False)[
    ["name", "owners_mid", "num_reviews_total", "peak_ccu"]
].head(10)

                         name   owners_mid  num_reviews_total  peak_ccu
2                      Dota 2  350000000.0            2452595    555977
0            Counter-Strike 2  150000000.0            8632939   1212356
60        New World: Aeternum   75000000.0             244917     10420
1         PUBG: BATTLEGROUNDS   75000000.0            2513842    616738
25                   Unturned   75000000.0             552875     13530
3   Grand Theft Auto V Legacy   75000000.0            1803832    117698
42                   Palworld   75000000.0             314689     33835
34              Call of Duty®   75000000.0             379855     56993
82                   Lost Ark   75000000.0             201669     21875
10         Black Myth: Wukong   75000000.0             825621     35990

Elimino che non ha anno

In [13]:

df_s2["release_date_parsed"] = pd.to_datetime(
    df_s2["release_date"], errors="coerce"
)
df_s2["release_year"] = df_s2["release_date_parsed"].dt.year

# Quante righe senza anno
df_s2["release_year"].isna().sum()

np.int64(0)

In [14]:
# Range anni e valori estremi
df_s2["release_year"].min(), df_s2["release_year"].max()

(1997, 2025)

In [15]:
# 10 anni più frequenti
df_s2["release_year"].value_counts().sort_values(ascending=False).head(10)

release_year
2024    18282
2023    12735
2022     9158
2020     8568
2021     8294
2018     7443
2019     6146
2017     5967
2016     4160
2025     3573
Name: count, dtype: int64

zeri nel gruppi

In [16]:

playtime_cols = [
    "average_playtime_forever",
    "median_playtime_forever"
]

# percentuale di zeri
def zero_ratio(series):
    return (series == 0).mean()

# Calcolo zeri di playtime per owners_tier
playtime_by_tier = (
    df_s2
    .groupby("owners_tier")[playtime_cols]
    .apply(lambda x: x.apply(zero_ratio))
    .sort_index()
)

playtime_by_tier

             average_playtime_forever  median_playtime_forever
owners_tier
100M–200M                    0.000000                 0.000000
200M+                        0.000000                 0.000000
200k–2M                      0.421220                 0.421220
20M–50M                      0.291667                 0.291667
20k–200k                     0.776740                 0.776740
2M–20M                       0.397706                 0.397706
50M–100M                     0.500000                 0.500000
≤20k                         0.978446                 0.978446

In [17]:
# Definizione gioconi (>= 2M owners)
big_games = df_s2[df_s2["owners_mid"] >= 2_000_000]

big_games.shape

(559, 29)

In [18]:
# Percentuale di zeri nei big games
big_games[playtime_cols].apply(zero_ratio)

average_playtime_forever    0.39356
median_playtime_forever     0.39356
dtype: float64

In [19]:
# Colonna di riferimento
playtime_col = "average_playtime_forever"

# Aggregazione: totale giochi vs giochi con playtime > 0
playtime_count_by_tier = (
    df_s2
    .groupby("owners_tier")
    .agg(
        total_games = ("appid", "count"),
        games_with_playtime = (playtime_col, lambda x: (x > 0).sum())
    )
    .reset_index()
)

playtime_count_by_tier

  owners_tier  total_games  games_with_playtime
0   100M–200M            1                    1
1       200M+            1                    1
2     200k–2M         4081                 2362
3     20M–50M           24                   17
4    20k–200k        17240                 3849
5      2M–20M          523                  315
6    50M–100M           10                    5
7        ≤20k        67738                 1460

In [20]:
# Conteggio valori mancanti per colonna
na_count = df_s2.isna().sum()

# Percentuale di valori mancanti
na_pct = df_s2.isna().mean()

# Tabella riassuntiva ordinata
missing_summary = (
    pd.DataFrame({
        "missing_count": na_count,
        "missing_pct": na_pct
    })
    .sort_values("missing_pct", ascending=False)
)

missing_summary

                          missing_count  missing_pct
appid                                 0          0.0
name                                  0          0.0
release_date                          0          0.0
price                                 0          0.0
dlc_count                             0          0.0
discount                              0          0.0
required_age                          0          0.0
categories                            0          0.0
genres                                0          0.0
tags                                  0          0.0
positive                              0          0.0
negative                              0          0.0
num_reviews_total                     0          0.0
pct_pos_total                         0          0.0
peak_ccu                              0          0.0
average_playtime_forever              0          0.0
median_playtime_forever               0          0.0
average_playtime_2weeks               0          0.0
median_playtime_2weeks                0          0.0
estimated_owners                      0          0.0
pct_pos_recent                        0          0.0
num_reviews_recent                    0          0.0
achievements                          0          0.0
owners_low                            0          0.0
owners_high                           0          0.0
owners_mid                            0          0.0
owners_tier                           0          0.0
release_date_parsed                   0          0.0
release_year                          0          0.0

In [21]:
# Selezione colonne numeriche
numeric_cols = df_s2.select_dtypes(include=["int64", "float64"]).columns

# Tabella riassuntiva: totale, zeri, percentuale zeri
zero_summary = pd.DataFrame({
    "total_count": df_s2[numeric_cols].count(),
    "zero_count": (df_s2[numeric_cols] == 0).sum(),
    "zero_pct": (df_s2[numeric_cols] == 0).mean(),
    "non_zero_count": (df_s2[numeric_cols] != 0).sum()
}).sort_values("zero_pct", ascending=False)

zero_summary

                          total_count  zero_count  zero_pct  non_zero_count
average_playtime_2weeks         89618       88901  0.991999             717
median_playtime_2weeks          89618       88901  0.991999             717
required_age                    89618       88589  0.988518            1029
discount                        89618       82164  0.916825            7454
average_playtime_forever        89618       81608  0.910621            8010
median_playtime_forever         89618       81608  0.910621            8010
dlc_count                       89618       75388  0.841215           14230
peak_ccu                        89618       70698  0.788882           18920
owners_low                      89618       67738  0.755853           21880
achievements                    89618       41090  0.458502           48528
negative                        89618       30396  0.339173           59222
positive                        89618       19425  0.216753           70193
price                           89618       14160  0.158004           75458
owners_high                     89618        8418  0.093932           81200
owners_mid                      89618        8418  0.093932           81200
pct_pos_total                   89618          18  0.000201           89600
pct_pos_recent                  89618           2  0.000022           89616
appid                           89618           0  0.000000           89618
num_reviews_total               89618           0  0.000000           89618
num_reviews_recent              89618           0  0.000000           89618

Droppo colonne inutili

In [22]:
cols_to_drop = [
    "release_date",
    "discount",
    "required_age",
    "tags",
    "achievements",
    "release_date_parsed"
]

df_s2 = df_s2.drop(columns=cols_to_drop)

df_s2.shape

(89618, 23)

Riassunto numeriche

In [23]:
import pandas as pd

# selezione colonne numeriche
numeric_cols = df_s2.select_dtypes(include=["int64", "float64"]).columns

numeric_summary = pd.DataFrame({
    "variable": numeric_cols,
    "non_zero_count": [(df_s2[c] != 0).sum() for c in numeric_cols],
    "dtype": [df_s2[c].dtype for c in numeric_cols]
}).sort_values("non_zero_count", ascending=False)

numeric_summary

                    variable  non_zero_count    dtype
0                      appid           89618    int64
5          num_reviews_total           89618    int64
13        num_reviews_recent           89618    int64
12            pct_pos_recent           89616    int64
6              pct_pos_total           89600    int64
16                owners_mid           81200  float64
15               owners_high           81200    int64
1                      price           75458  float64
3                   positive           70193    int64
4                   negative           59222    int64
14                owners_low           21880    int64
7                   peak_ccu           18920    int64
2                  dlc_count           14230    int64
8   average_playtime_forever            8010    int64
9    median_playtime_forever            8010    int64
11    median_playtime_2weeks             717    int64
10   average_playtime_2weeks             717    int64

In [24]:
# selezione colonne non numeriche
non_numeric_cols = df_s2.select_dtypes(exclude=["int64", "float64"]).columns

non_numeric_summary = pd.DataFrame({
    "variable": non_numeric_cols,
    "non_na_count": [df_s2[c].notna().sum() for c in non_numeric_cols],
    "dtype": [df_s2[c].dtype for c in non_numeric_cols]
}).sort_values("non_na_count", ascending=False)

non_numeric_summary

           variable  non_na_count   dtype
0              name         89618  object
1        categories         89618  object
2            genres         89618  object
3  estimated_owners         89618  object
4       owners_tier         89618  object
5      release_year         89618   int32

## ANALYZE

Distribuzione di owners_mid

In [25]:
# Statistiche descrittive di base per owners_mid
owners_desc = df_s2["owners_mid"].describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99])

owners_desc

count    8.961800e+04
mean     1.011338e+05
std      1.677279e+06
min      0.000000e+00
25%      1.000000e+04
50%      1.000000e+04
75%      1.000000e+04
90%      7.500000e+04
95%      3.500000e+05
99%      1.500000e+06
max      3.500000e+08
Name: owners_mid, dtype: float64

In [26]:
# Quantili personalizzati
quantiles = df_s2["owners_mid"].quantile(
    [0.5, 0.75, 0.9, 0.95, 0.99, 0.999]
)

quantiles

0.500      10000.0
0.750      10000.0
0.900      75000.0
0.950     350000.0
0.990    1500000.0
0.999    7500000.0
Name: owners_mid, dtype: float64

In [27]:
# Percentuale di giochi sopra alcune soglie di owners
thresholds = [20_000, 200_000, 2_000_000, 20_000_000]

owners_thresholds = {
    f">= {t}": (df_s2["owners_mid"] >= t).mean()
    for t in thresholds
}

owners_thresholds

{'>= 20000': np.float64(0.24414738110647416),
 '>= 200000': np.float64(0.051775312995157224),
 '>= 2000000': np.float64(0.006237586199201053),
 '>= 20000000': np.float64(0.00040170501461759915)}

Distribuzione di owners_tier

In [28]:
owners_tier_order = [
    "≤20k",
    "20k–200k",
    "200k–2M",
    "2M–20M",
    "20M–50M",
    "50M–100M",
    "100M–200M",
    "200M+",
]

In [29]:
df_s2["owners_tier"] = pd.Categorical(
    df_s2["owners_tier"],
    categories=owners_tier_order,
    ordered=True
)

In [30]:
# Distribuzione assoluta (ordine crescente corretto)
owners_tier_dist = df_s2["owners_tier"].value_counts(sort=False)

owners_tier_dist

owners_tier
≤20k         67738
20k–200k     17240
200k–2M       4081
2M–20M         523
20M–50M         24
50M–100M        10
100M–200M        1
200M+            1
Name: count, dtype: int64

In [31]:
owners_tier_pct = df_s2["owners_tier"].value_counts(normalize=True, sort=False)

owners_tier_pct

owners_tier
≤20k         0.755853
20k–200k     0.192372
200k–2M      0.045538
2M–20M       0.005836
20M–50M      0.000268
50M–100M     0.000112
100M–200M    0.000011
200M+        0.000011
Name: proportion, dtype: float64

Distribuzione di num_reviews_total

In [32]:
# Statistiche descrittive per num_reviews_total
reviews_desc = df_s2["num_reviews_total"].describe(
    percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99]
)

reviews_desc

count    8.961800e+04
mean     1.315490e+03
std      3.542370e+04
min     -1.000000e+00
25%     -1.000000e+00
50%      1.500000e+01
75%      8.100000e+01
90%      5.100000e+02
95%      1.756150e+03
99%      1.808665e+04
max      8.632939e+06
Name: num_reviews_total, dtype: float64

In [33]:
reviews_quantiles = df_s2["num_reviews_total"].quantile(
    [0.5, 0.75, 0.9, 0.95, 0.99, 0.999]
)

reviews_quantiles

0.500        15.000
0.750        81.000
0.900       510.000
0.950      1756.150
0.990     18086.650
0.999    178419.688
Name: num_reviews_total, dtype: float64

In [34]:
review_thresholds = {
    ">= 10 reviews": (df_s2["num_reviews_total"] >= 10).mean(),
    ">= 100 reviews": (df_s2["num_reviews_total"] >= 100).mean(),
    ">= 1k reviews": (df_s2["num_reviews_total"] >= 1000).mean(),
    ">= 10k reviews": (df_s2["num_reviews_total"] >= 10000).mean(),
}

review_thresholds

{'>= 10 reviews': np.float64(0.5936195853511571),
 '>= 100 reviews': np.float64(0.227443147581959),
 '>= 1k reviews': np.float64(0.06953960141935772),
 '>= 10k reviews': np.float64(0.015867348077395167)}

Distribuzione di pct_pos_total

In [35]:
# Statistiche descrittive per pct_pos_total
pct_desc = df_s2["pct_pos_total"].describe(
    percentiles=[0.1, 0.25, 0.5, 0.75, 0.9]
)

pct_desc

count    89618.000000
mean        45.352418
std         40.685695
min         -1.000000
10%         -1.000000
25%         -1.000000
50%         60.000000
75%         84.000000
90%         93.000000
max        100.000000
Name: pct_pos_total, dtype: float64

In [36]:
pct_thresholds = {
    ">= 50% positive": (df_s2["pct_pos_total"] >= 50).mean(),
    ">= 70% positive": (df_s2["pct_pos_total"] >= 70).mean(),
    ">= 90% positive": (df_s2["pct_pos_total"] >= 90).mean(),
}

pct_thresholds

{'>= 50% positive': np.float64(0.547166863799683),
 '>= 70% positive': np.float64(0.42752572027940816),
 '>= 90% positive': np.float64(0.17357004173268764)}

verifica coerenza free 2 play

In [37]:
# Flag: il genere contiene "Free to Play"
df_s2["is_free_genre"] = df_s2["genres"].str.contains(
    "Free to Play", case=False, na=False
)

In [38]:
# Flag: prezzo zero
df_s2["is_free_price"] = df_s2["price"] == 0

In [39]:
free_consistency = pd.crosstab(
    df_s2["is_free_genre"],
    df_s2["is_free_price"],
    rownames=["Free_to_Play_in_Genres"],
    colnames=["Price_is_0"]
)

free_consistency

Price_is_0              False  True
Free_to_Play_in_Genres
False                   75386   5365
True                       72   8795

In [40]:
free_consistency_pct = free_consistency.div(
    free_consistency.sum(axis=1), axis=0
)

free_consistency_pct

Price_is_0                 False     True
Free_to_Play_in_Genres
False                   0.933561  0.066439
True                    0.008120  0.991880

In [41]:
f2p_genre_paid = df_s2[
    (df_s2["is_free_genre"]) & (df_s2["price"] > 0)
][["name", "price", "genres"]].head(10)

f2p_genre_paid

,name,price,genres
2552,The Spell Brigade,9.99,"['Action', 'Casual', 'Indie', 'Free To Play', ..."
4091,Dear Esther: Landmark Edition,9.99,"['Adventure', 'Casual', 'Indie', 'Free To Play']"
4179,CATO: Buttered Cat,10.99,"['Adventure', 'Casual', 'Indie', 'Free To Play']"
5080,Journey to the West,19.99,"['Adventure', 'Indie', 'RPG', 'Strategy', 'Fre..."
7417,CONVRGENCE,19.99,"['Action', 'Adventure', 'Free To Play', 'Early..."
10479,Horizon,5.99,"['Adventure', 'Indie', 'Simulation', 'Strategy..."
11553,Space Simulation Toolkit,19.99,"['Indie', 'Simulation', 'Free To Play', 'Early..."
14774,Doomsday Robot Girl,7.14,"['Simulation', 'Free To Play']"
14911,Elisa: Seduce the Innkeeper,2.49,"['Adventure', 'Casual', 'Indie', 'Free To Play']"
17374,BLOCKPOST MOBILE,4.99,"['Action', 'Indie', 'Massively Multiplayer', '..."

In [42]:
free_price_no_genre = df_s2[
    (df_s2["price"] == 0) & (~df_s2["is_free_genre"])
][["name", "price", "genres", "categories"]].head(10)

free_price_no_genre

,name,price,genres,categories
3,Grand Theft Auto V Legacy,0.0,"['Action', 'Adventure']","['Single-player', 'Multi-player', 'PvP', 'Onli..."
28,Fall Guys,0.0,"['Action', 'Casual', 'Indie', 'Massively Multi...","['Multi-player', 'MMO', 'PvP', 'Online PvP', '..."
30,Rocket League®,0.0,"['Action', 'Indie', 'Racing', 'Sports']","['Single-player', 'Multi-player', 'PvP', 'Onli..."
34,Call of Duty®,0.0,['Action'],"['Single-player', 'Multi-player', 'PvP', 'Onli..."
50,NARAKA: BLADEPOINT,0.0,"['Action', 'Adventure', 'Massively Multiplayer']","['Multi-player', 'PvP', 'Online PvP', 'Steam A..."
93,It Takes Two Friend's Pass,0.0,"['Action', 'Adventure', 'Indie']","['Multi-player', 'Co-op', 'Online Co-op', 'Sha..."
97,Life is Strange - Episode 1,0.0,"['Action', 'Adventure']","['Single-player', 'Steam Achievements', 'Full ..."
138,FIFA 22,0.0,"['Simulation', 'Sports']","['Single-player', 'Multi-player', 'MMO', 'PvP'..."
180,Monster Hunter Wilds Beta test,0.0,[],[]
181,Poppy Playtime,0.0,"['Action', 'Adventure', 'Indie']",['Single-player']

In [43]:
# Conteggio giochi Free to Play (da genres) e prezzo = 0
both_f2p_and_free = df_s2[
    (df_s2["is_free_genre"]) & (df_s2["price"] == 0)
].shape[0]

# Conteggio giochi con prezzo = 0 ma NON Free to Play
free_price_only = df_s2[
    (df_s2["price"] == 0) & (~df_s2["is_free_genre"])
].shape[0]

both_f2p_and_free, free_price_only

(8795, 5365)

In [44]:
f2p_summary = pd.DataFrame({
    "category": [
        "Free to Play (genre) AND price = 0",
        "Price = 0 BUT NOT Free to Play (genre)"
    ],
    "count": [
        both_f2p_and_free,
        free_price_only
    ]
})

f2p_summary

                                 category  count
0      Free to Play (genre) AND price = 0   8795
1  Price = 0 BUT NOT Free to Play (genre)   5365

In [45]:
# Numero totale di giochi con prezzo = 0
num_price_zero = (df_s2["price"] == 0).sum()

# Percentuale sul totale
pct_price_zero = (df_s2["price"] == 0).mean()

num_price_zero, pct_price_zero

(np.int64(14160), np.float64(0.15800397241625566))

In [46]:
# Gruppo A: tutti i giochi con prezzo = 0
group_price_zero = df_s2[df_s2["price"] == 0]

# Gruppo B: sottoinsieme Free-to-Play (genre) con prezzo = 0
group_f2p = df_s2[
    (df_s2["price"] == 0) & (df_s2["is_free_genre"])
]

In [47]:
len(group_price_zero), len(group_f2p)

(14160, 8795)

In [48]:
price0_vs_f2p_tier = pd.DataFrame({
    "price_0_all": group_price_zero["owners_tier"].value_counts(sort=False),
    "price_0_f2p_only": group_f2p["owners_tier"].value_counts(sort=False)
}).fillna(0).astype(int)

price0_vs_f2p_tier

             price_0_all  price_0_f2p_only
owners_tier
≤20k               10757              6511
20k–200k            2528              1603
200k–2M              731               564
2M–20M               129               106
20M–50M                7                 5
50M–100M               6                 4
100M–200M              1                 1
200M+                  1                 1

In [49]:
price0_vs_f2p_tier_pct = price0_vs_f2p_tier.div(
    price0_vs_f2p_tier.sum(), axis=1
)

price0_vs_f2p_tier_pct

             price_0_all  price_0_f2p_only
owners_tier
≤20k            0.759675          0.740307
20k–200k        0.178531          0.182263
200k–2M         0.051624          0.064127
2M–20M          0.009110          0.012052
20M–50M         0.000494          0.000569
50M–100M        0.000424          0.000455
100M–200M       0.000071          0.000114
200M+           0.000071          0.000114

In [50]:
top_tiers = [
    "20M–50M",
    "50M–100M",
    "100M–200M",
    "200M+"
]

In [51]:
def print_games_for_tier(tier):
    print(f"\n==============================")
    print(f"OWNERS TIER: {tier}")
    print(f"==============================\n")

    # Tutti i giochi price = 0
    print(">>> PRICE = 0 (ALL)")
    display(
        group_price_zero[
            group_price_zero["owners_tier"] == tier
        ][["name", "owners_mid", "price", "genres"]]
        .sort_values("owners_mid", ascending=False)
    )

    # Solo Free-to-Play veri
    print("\n>>> PRICE = 0 AND FREE-TO-PLAY (GENRE)")
    display(
        group_f2p[
            group_f2p["owners_tier"] == tier
        ][["name", "owners_mid", "price", "genres",]]
        .sort_values("owners_mid", ascending=False)
    )

In [52]:
for tier in top_tiers:
    print_games_for_tier(tier)

==============================
OWNERS TIER: 20M–50M
==============================

>>> PRICE = 0 (ALL)

,name,owners_mid,price,genres
5,Team Fortress 2,35000000.0,0.0,"['Action', 'Free To Play']"
19,Destiny 2,35000000.0,0.0,"['Action', 'Adventure', 'Free To Play']"
23,War Thunder,35000000.0,0.0,"['Action', 'Massively Multiplayer', 'Simulatio..."
28,Fall Guys,35000000.0,0.0,"['Action', 'Casual', 'Indie', 'Massively Multi..."
33,Brawlhalla,35000000.0,0.0,"['Action', 'Indie', 'Free To Play']"
50,NARAKA: BLADEPOINT,35000000.0,0.0,"['Action', 'Adventure', 'Massively Multiplayer']"
64,Path of Exile,35000000.0,0.0,"['Action', 'Adventure', 'Indie', 'Massively Mu..."

>>> PRICE = 0 AND FREE-TO-PLAY (GENRE)

,name,owners_mid,price,genres
5,Team Fortress 2,35000000.0,0.0,"['Action', 'Free To Play']"
19,Destiny 2,35000000.0,0.0,"['Action', 'Adventure', 'Free To Play']"
23,War Thunder,35000000.0,0.0,"['Action', 'Massively Multiplayer', 'Simulatio..."
33,Brawlhalla,35000000.0,0.0,"['Action', 'Indie', 'Free To Play']"
64,Path of Exile,35000000.0,0.0,"['Action', 'Adventure', 'Indie', 'Massively Mu..."

==============================
OWNERS TIER: 50M–100M
==============================

>>> PRICE = 0 (ALL)

,name,owners_mid,price,genres
1,PUBG: BATTLEGROUNDS,75000000.0,0.0,"['Action', 'Adventure', 'Massively Multiplayer..."
3,Grand Theft Auto V Legacy,75000000.0,0.0,"['Action', 'Adventure']"
9,Apex Legends™,75000000.0,0.0,"['Action', 'Adventure', 'Free To Play']"
25,Unturned,75000000.0,0.0,"['Action', 'Adventure', 'Casual', 'Indie', 'Fr..."
34,Call of Duty®,75000000.0,0.0,['Action']
82,Lost Ark,75000000.0,0.0,"['Action', 'Adventure', 'Massively Multiplayer..."

>>> PRICE = 0 AND FREE-TO-PLAY (GENRE)

,name,owners_mid,price,genres
1,PUBG: BATTLEGROUNDS,75000000.0,0.0,"['Action', 'Adventure', 'Massively Multiplayer..."
9,Apex Legends™,75000000.0,0.0,"['Action', 'Adventure', 'Free To Play']"
25,Unturned,75000000.0,0.0,"['Action', 'Adventure', 'Casual', 'Indie', 'Fr..."
82,Lost Ark,75000000.0,0.0,"['Action', 'Adventure', 'Massively Multiplayer..."

==============================
OWNERS TIER: 100M–200M
==============================

>>> PRICE = 0 (ALL)

               name   owners_mid  price                      genres
0  Counter-Strike 2  150000000.0    0.0  ['Action', 'Free To Play']

>>> PRICE = 0 AND FREE-TO-PLAY (GENRE)

               name   owners_mid  price                      genres
0  Counter-Strike 2  150000000.0    0.0  ['Action', 'Free To Play']

==============================
OWNERS TIER: 200M+
==============================

>>> PRICE = 0 (ALL)

     name   owners_mid  price                                  genres
2  Dota 2  350000000.0    0.0  ['Action', 'Strategy', 'Free To Play']

>>> PRICE = 0 AND FREE-TO-PLAY (GENRE)

     name   owners_mid  price                                  genres
2  Dota 2  350000000.0    0.0  ['Action', 'Strategy', 'Free To Play']

Distribuzione di price

In [53]:
price_desc = df_s2["price"].describe(
    percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99]
)

price_desc

count    89618.000000
mean         7.309623
std         13.331073
min          0.000000
25%          0.990000
50%          4.990000
75%          9.990000
90%         15.990000
95%         19.990000
99%         39.990000
max        999.980000
Name: price, dtype: float64

In [54]:
price_thresholds = {
    "price = 0": (df_s2["price"] == 0).mean(),
    "0 < price ≤ 5": ((df_s2["price"] > 0) & (df_s2["price"] <= 5)).mean(),
    "5 < price ≤ 10": ((df_s2["price"] > 5) & (df_s2["price"] <= 10)).mean(),
    "10 < price ≤ 20": ((df_s2["price"] > 10) & (df_s2["price"] <= 20)).mean(),
    "20 < price ≤ 40": ((df_s2["price"] > 20) & (df_s2["price"] <= 40)).mean(),
    "price > 40": (df_s2["price"] > 40).mean(),
}

price_thresholds

{'price = 0': np.float64(0.15800397241625566),
 '0 < price ≤ 5': np.float64(0.44026869602088864),
 '5 < price ≤ 10': np.float64(0.21251311120533822),
 '10 < price ≤ 20': np.float64(0.1419692472494365),
 '20 < price ≤ 40': np.float64(0.037291615523667124),
 'price > 40': np.float64(0.009953357584413845)}

In [55]:
df_s2["price"].sort_values(ascending=False).head(10)

60133    999.98
81168    999.98
64631    999.00
84664    500.00
72266    299.90
72597    269.99
72863    249.00
54286    219.00
57518    199.99
62568    199.99
Name: price, dtype: float64

Distribuzione di release_year

In [56]:
# Conteggio giochi per release_year
year_dist = (
    df_s2["release_year"]
    .value_counts()
    .sort_index()
)

year_dist

release_year
1997        2
1999        1
2001        2
2002        1
2003        2
2004        2
2005        4
2006        9
2007        8
2008        7
2009       63
2010      164
2011      212
2012      309
2013      460
2014     1525
2015     2521
2016     4160
2017     5967
2018     7443
2019     6146
2020     8568
2021     8294
2022     9158
2023    12735
2024    18282
2025     3573
Name: count, dtype: int64

In [57]:
year_dist_pct = year_dist / year_dist.sum()

year_dist_pct

release_year
1997    0.000022
1999    0.000011
2001    0.000022
2002    0.000011
2003    0.000022
2004    0.000022
2005    0.000045
2006    0.000100
2007    0.000089
2008    0.000078
2009    0.000703
2010    0.001830
2011    0.002366
2012    0.003448
2013    0.005133
2014    0.017017
2015    0.028131
2016    0.046419
2017    0.066583
2018    0.083053
2019    0.068580
2020    0.095606
2021    0.092548
2022    0.102189
2023    0.142103
2024    0.203999
2025    0.039869
Name: count, dtype: float64

In [58]:
year_cumulative = year_dist_pct.cumsum()

year_cumulative

release_year
1997    0.000022
1999    0.000033
2001    0.000056
2002    0.000067
2003    0.000089
2004    0.000112
2005    0.000156
2006    0.000257
2007    0.000346
2008    0.000424
2009    0.001127
2010    0.002957
2011    0.005323
2012    0.008771
2013    0.013903
2014    0.030920
2015    0.059051
2016    0.105470
2017    0.172052
2018    0.255105
2019    0.323685
2020    0.419291
2021    0.511839
2022    0.614028
2023    0.756132
2024    0.960131
2025    1.000000
Name: count, dtype: float64

## RQ1

Confronto Free (price = 0) vs Paid (price > 0)

In [59]:
# Flag Free vs Paid (decisione fissata)
df_s2["is_free"] = df_s2["price"] == 0

# Controllo rapido
df_s2["is_free"].value_counts()

is_free
False    75458
True     14160
Name: count, dtype: int64

In [60]:
owners_by_free = (
    df_s2
    .groupby("is_free")["owners_mid"]
    .describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99])
)

owners_by_free

,count,mean,std,min,25%,50%,75%,90%,95%,99%,max
is_free,,,,,,,,,,,
False,75458.0,85550.438655,8.812846e+05,0.0,10000.0,10000.0,10000.0,75000.0,150000.0,1500000.0,75000000.0
True,14160.0,184176.553672,3.695790e+06,0.0,0.0,0.0,10000.0,75000.0,350000.0,3500000.0,350000000.0

In [61]:
owners_tier_by_free = (
    df_s2
    .groupby(["is_free", "owners_tier"])
    .size()
    .unstack(fill_value=0)
)

owners_tier_by_free

/tmp/ipython-input-1837868457.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["is_free", "owners_tier"])

owners_tier,≤20k,20k–200k,200k–2M,2M–20M,20M–50M,50M–100M,100M–200M,200M+
is_free,,,,,,,,
False,56981,14712,3350,394,17,4,0,0
True,10757,2528,731,129,7,6,1,1

In [62]:
owners_tier_by_free_pct = owners_tier_by_free.div(
    owners_tier_by_free.sum(axis=1), axis=0
)

owners_tier_by_free_pct

owners_tier,≤20k,20k–200k,200k–2M,2M–20M,20M–50M,50M–100M,100M–200M,200M+
is_free,,,,,,,,
False,0.755135,0.194969,0.044396,0.005221,0.000225,0.000053,0.000000,0.000000
True,0.759675,0.178531,0.051624,0.009110,0.000494,0.000424,0.000071,0.000071

Engagement: num_reviews_total

In [63]:
reviews_by_free = (
    df_s2
    .groupby("is_free")["num_reviews_total"]
    .describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99])
)

reviews_by_free

,count,mean,std,min,25%,50%,75%,90%,95%,99%,max
is_free,,,,,,,,,,,
False,75458.0,1040.614435,14810.840627,-1.0,-1.0,13.0,69.00,457.3,1586.15,16082.89,1168020.0
True,14160.0,2780.290325,82284.304336,-1.0,12.0,35.0,144.25,846.1,2781.35,29593.08,8632939.0

In [64]:
review_thresholds_by_free = (
    df_s2
    .assign(
        has_100_reviews=df_s2["num_reviews_total"] >= 100,
        has_1k_reviews=df_s2["num_reviews_total"] >= 1000,
        has_10k_reviews=df_s2["num_reviews_total"] >= 10000
    )
    .groupby("is_free")[["has_100_reviews", "has_1k_reviews", "has_10k_reviews"]]
    .mean()
)

review_thresholds_by_free

         has_100_reviews  has_1k_reviews  has_10k_reviews
is_free
False           0.213563        0.065334         0.014710
True            0.301412        0.091949         0.022034

Qualità percepita (pct_pos_total)

In [65]:
# Flag: gioco con valutazione disponibile
df_s2["has_rating"] = df_s2["pct_pos_total"] >= 0

# Percentuale di giochi con rating per Free vs Paid
rating_availability = (
    df_s2
    .groupby("is_free")["has_rating"]
    .mean()
)

rating_availability

is_free
False    0.553553
True     0.807133
Name: has_rating, dtype: float64

In [66]:
# Sottodataset: solo giochi con rating valido
rated_games = df_s2[df_s2["pct_pos_total"] >= 0]

# Statistiche descrittive per Free vs Paid
pct_by_free = (
    rated_games
    .groupby("is_free")["pct_pos_total"]
    .describe(percentiles=[0.25, 0.5, 0.75, 0.9])
)

pct_by_free

           count       mean        std  min   25%   50%   75%   90%    max
is_free
False    41770.0  77.267537  17.906444  0.0  68.0  81.0  91.0  96.0  100.0
True     11429.0  76.414997  16.552334  1.0  66.0  80.0  90.0  95.0  100.0

In [67]:
quality_thresholds = (
    rated_games
    .assign(
        good_70=rated_games["pct_pos_total"] >= 70,
        excellent_90=rated_games["pct_pos_total"] >= 90
    )
    .groupby("is_free")[["good_70", "excellent_90"]]
    .mean()
)

quality_thresholds

          good_70  excellent_90
is_free
False    0.726047      0.300982
True     0.698836      0.261003

Dimensione temporale (release_year)

In [68]:
release_year_by_free = (
    df_s2
    .groupby("is_free")["release_year"]
    .describe(percentiles=[0.25, 0.5, 0.75])
)

release_year_by_free

,count,mean,std,min,25%,50%,75%,max
is_free,,,,,,,,
False,75458.0,2020.709096,3.122358,1997.0,2018.0,2021.0,2023.0,2025.0
True,14160.0,2021.022387,2.902370,1997.0,2019.0,2022.0,2024.0,2025.0

In [69]:
free_share_by_year = (
    df_s2
    .groupby("release_year")["is_free"]
    .mean()
)

free_share_by_year

release_year
1997    0.500000
1999    0.000000
2001    0.000000
2002    0.000000
2003    0.000000
2004    0.500000
2005    0.000000
2006    0.000000
2007    0.125000
2008    0.142857
2009    0.047619
2010    0.091463
2011    0.094340
2012    0.106796
2013    0.097826
2014    0.081967
2015    0.111860
2016    0.142308
2017    0.151165
2018    0.159210
2019    0.152131
2020    0.162582
2021    0.150952
2022    0.171544
2023    0.166156
2024    0.172574
2025    0.148894
Name: is_free, dtype: float64

In [70]:
free_share_by_year_success = (
    df_s2[df_s2["owners_mid"] >= 200_000]
    .groupby("release_year")["is_free"]
    .mean()
)

free_share_by_year_success

release_year
1997    1.000000
1999    0.000000
2001    0.000000
2002    0.000000
2004    0.500000
2005    0.000000
2006    0.000000
2007    0.250000
2008    0.250000
2009    0.142857
2010    0.133333
2011    0.112245
2012    0.134146
2013    0.138393
2014    0.175676
2015    0.230769
2016    0.208333
2017    0.250575
2018    0.264706
2019    0.289634
2020    0.245370
2021    0.167553
2022    0.093190
2023    0.054054
2024    0.049618
2025    0.200000
Name: is_free, dtype: float64

In [71]:
df_s2["release_era"] = pd.cut(
    df_s2["release_year"],
    bins=[1996, 2009, 2014, 2018, 2021, 2025],
    labels=["pre-2010", "2010–2014", "2015–2018", "2019–2021", "2022–2025"]
)

free_share_by_era = (
    df_s2
    .groupby("release_era")["is_free"]
    .mean()
)

free_share_by_era

/tmp/ipython-input-1511760704.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("release_era")["is_free"]

release_era
pre-2010     0.069307
2010–2014    0.089139
2015–2018    0.147379
2019–2021    0.155598
2022–2025    0.168556
Name: is_free, dtype: float64

## RQ2

Longevità & Playtime >= 200k

In [72]:
# Sottodataset per B2: giochi con successo (owners >= 200k)
df_b2 = df_s2[df_s2["owners_mid"] >= 200_000].copy()

df_b2.shape

(4640, 28)

In [73]:
playtime_availability = {
    "playtime_forever_available": (df_b2["average_playtime_forever"] > 0).mean(),
    "playtime_2weeks_available": (df_b2["average_playtime_2weeks"] > 0).mean(),
}

playtime_availability

{'playtime_forever_available': np.float64(0.5821120689655173),
 'playtime_2weeks_available': np.float64(0.11745689655172414)}

SP vs MP

In [74]:
import ast

def extract_unique_elements(series):
    elements = set()
    for x in series.dropna():
        try:
            parsed = ast.literal_eval(x)
            if isinstance(parsed, list):
                for item in parsed:
                    elements.add(item.strip())
        except:
            pass
    return elements

# Estrai elementi unici
genres_set = extract_unique_elements(df_b2["genres"])
categories_set = extract_unique_elements(df_b2["categories"])

# Unione
all_labels = sorted(genres_set.union(categories_set))

# Output
len(all_labels), all_labels

(66,
 ['Action',
  'Adventure',
  'Animation & Modeling',
  'Audio Production',
  'Captions available',
  'Casual',
  'Co-op',
  'Commentary available',
  'Cross-Platform Multiplayer',
  'Design & Illustration',
  'Early Access',
  'Education',
  'Family Sharing',
  'Free To Play',
  'Full controller support',
  'Game Development',
  'Gore',
  'HDR available',
  'In-App Purchases',
  'Includes Source SDK',
  'Includes level editor',
  'Indie',
  'LAN Co-op',
  'LAN PvP',
  'MMO',
  'Massively Multiplayer',
  'Movie',
  'Multi-player',
  'Nudity',
  'Online Co-op',
  'Online PvP',
  'Partial Controller Support',
  'Photo Editing',
  'PvP',
  'RPG',
  'Racing',
  'Remote Play Together',
  'Remote Play on Phone',
  'Remote Play on TV',
  'Remote Play on Tablet',
  'Shared/Split Screen',
  'Shared/Split Screen Co-op',
  'Shared/Split Screen PvP',
  'Simulation',
  'Single-player',
  'Software Training',
  'Sports',
  'Stats',
  'Steam Achievements',
  'Steam Cloud',
  'Steam Leaderboards',
  'Steam Timeline',
  'Steam Trading Cards',
  'Steam Turn Notifications',
  'Steam Workshop',
  'SteamVR Collectibles',
  'Strategy',
  'Tracked Controller Support',
  'Utilities',
  'VR Only',
  'VR Support',
  'VR Supported',
  'Valve Anti-Cheat enabled',
  'Video Production',
  'Violent',
  'Web Publishing'])

In [75]:
mp_labels = [
    "Multi-player",
    "Massively Multiplayer",
    "MMO",
    "Online PvP",
    "Online Co-op",
    "LAN PvP",
    "LAN Co-op",
    "PvP",
    "Shared/Split Screen PvP",
    "Shared/Split Screen Co-op",
    "Co-op",
    "Cross-Platform Multiplayer"
]

def classify_mode(categories):
    if not isinstance(categories, str):
        return "Other"

    has_sp = "Single-player" in categories
    has_mp = any(label in categories for label in mp_labels)

    if has_sp and has_mp:
        return "Hybrid (SP+MP)"
    elif has_mp:
        return "Multiplayer only"
    elif has_sp:
        return "Single-player only"
    else:
        return "Other"

df_b2["game_mode"] = df_b2["categories"].apply(classify_mode)

# Controllo distribuzione
df_b2["game_mode"].value_counts()

game_mode
Single-player only    2598
Hybrid (SP+MP)        1587
Multiplayer only       409
Other                   46
Name: count, dtype: int64

Playtime FOREVER (confronto tra i 3 gruppi)

In [76]:
# Sottodataset con playtime_forever disponibile
df_play_forever = df_b2[df_b2["average_playtime_forever"] > 0]

playtime_forever_stats = (
    df_play_forever
    .groupby("game_mode")["average_playtime_forever"]
    .describe(percentiles=[0.25, 0.5, 0.75, 0.9])
)

playtime_forever_stats

,count,mean,std,min,25%,50%,75%,90%,max
game_mode,,,,,,,,,
Hybrid (SP+MP),948.0,1647.094937,3365.218785,1.0,240.00,603.0,1533.25,3620.6,50259.0
Multiplayer only,228.0,2026.907895,5539.916963,1.0,111.00,344.0,1279.50,4503.8,43031.0
Other,19.0,6418.210526,14164.835684,2.0,31.50,478.0,5065.50,14664.4,60288.0
Single-player only,1506.0,1515.543161,14833.821710,1.0,180.25,333.5,845.00,1887.5,533442.0

In [77]:
# (>=200k)
tiers_interest = ["200k–2M", "2M–20M", "20M–50M", "50M–100M", "100M–200M", "200M+"]

df_b2_tiers = df_b2[df_b2["owners_tier"].isin(tiers_interest)]

# Totale giochi per tier e modalità
total_by_tier_mode = (
    df_b2_tiers
    .groupby(["owners_tier", "game_mode"])
    .size()
    .unstack(fill_value=0)
)

total_by_tier_mode

/tmp/ipython-input-619471122.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["owners_tier", "game_mode"])

game_mode    Hybrid (SP+MP)  Multiplayer only  Other  Single-player only
owners_tier
≤20k                      0                 0      0                   0
20k–200k                  0                 0      0                   0
200k–2M                1324               309     42                2406
2M–20M                  242                88      3                 190
20M–50M                  16                 6      1                   1
50M–100M                  5                 4      0                   1
100M–200M                 0                 1      0                   0
200M+                     0                 1      0                   0

In [78]:
playtime_forever_available_by_tier = (
    df_b2_tiers[df_b2_tiers["average_playtime_forever"] > 0]
    .groupby(["owners_tier", "game_mode"])
    .size()
    .unstack(fill_value=0)
)

playtime_forever_available_by_tier

/tmp/ipython-input-2691261165.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["owners_tier", "game_mode"])

game_mode    Hybrid (SP+MP)  Multiplayer only  Other  Single-player only
owners_tier
≤20k                      0                 0      0                   0
20k–200k                  0                 0      0                   0
200k–2M                 796               159     19                1388
2M–20M                  135                63      0                 117
20M–50M                  14                 2      0                   1
50M–100M                  3                 2      0                   0
100M–200M                 0                 1      0                   0
200M+                     0                 1      0                   0

In [79]:
playtime_forever_pct_by_tier = (
    playtime_forever_available_by_tier / total_by_tier_mode
)

playtime_forever_pct_by_tier

game_mode    Hybrid (SP+MP)  Multiplayer only     Other  Single-player only
owners_tier
≤20k                    NaN               NaN       NaN                 NaN
20k–200k                NaN               NaN       NaN                 NaN
200k–2M            0.601208          0.514563  0.452381            0.576891
2M–20M             0.557851          0.715909  0.000000            0.615789
20M–50M            0.875000          0.333333  0.000000            1.000000
50M–100M           0.600000          0.500000       NaN            0.000000
100M–200M               NaN          1.000000       NaN                 NaN
200M+                   NaN          1.000000       NaN                 NaN

Playtime 2WEEKS (confronto tra i 3 gruppi)

In [80]:
# Totale giochi per tier e modalità (>=200k)
total_by_tier_mode_2w = (
    df_b2_tiers
    .groupby(["owners_tier", "game_mode"])
    .size()
    .unstack(fill_value=0)
)

total_by_tier_mode_2w

/tmp/ipython-input-4042744014.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["owners_tier", "game_mode"])

game_mode    Hybrid (SP+MP)  Multiplayer only  Other  Single-player only
owners_tier
≤20k                      0                 0      0                   0
20k–200k                  0                 0      0                   0
200k–2M                1324               309     42                2406
2M–20M                  242                88      3                 190
20M–50M                  16                 6      1                   1
50M–100M                  5                 4      0                   1
100M–200M                 0                 1      0                   0
200M+                     0                 1      0                   0

In [81]:
playtime_2w_available_by_tier = (
    df_b2_tiers[df_b2_tiers["average_playtime_2weeks"] > 0]
    .groupby(["owners_tier", "game_mode"])
    .size()
    .unstack(fill_value=0)
)

playtime_2w_available_by_tier

/tmp/ipython-input-3101950067.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["owners_tier", "game_mode"])

game_mode    Hybrid (SP+MP)  Multiplayer only  Other  Single-player only
owners_tier
≤20k                      0                 0      0                   0
20k–200k                  0                 0      0                   0
200k–2M                 151                18      6                 167
2M–20M                   85                30      0                  65
20M–50M                  14                 2      0                   1
50M–100M                  3                 1      0                   0
100M–200M                 0                 1      0                   0
200M+                     0                 1      0                   0

In [82]:
playtime_2w_pct_by_tier = (
    playtime_2w_available_by_tier / total_by_tier_mode_2w
)

playtime_2w_pct_by_tier

game_mode    Hybrid (SP+MP)  Multiplayer only     Other  Single-player only
owners_tier
≤20k                    NaN               NaN       NaN                 NaN
20k–200k                NaN               NaN       NaN                 NaN
200k–2M            0.114048          0.058252  0.142857            0.069410
2M–20M             0.351240          0.340909  0.000000            0.342105
20M–50M            0.875000          0.333333  0.000000            1.000000
50M–100M           0.600000          0.250000       NaN            0.000000
100M–200M               NaN          1.000000       NaN                 NaN
200M+                   NaN          1.000000       NaN                 NaN

In [83]:
df_play_2w = df_b2[df_b2["average_playtime_2weeks"] > 0]

playtime_2w_stats = (
    df_play_2w
    .groupby("game_mode")["average_playtime_2weeks"]
    .describe(percentiles=[0.25, 0.5, 0.75, 0.9])
)

playtime_2w_stats

,count,mean,std,min,25%,50%,75%,90%,max
game_mode,,,,,,,,,
Hybrid (SP+MP),253.0,547.687747,1217.112473,1.0,54.0,167.0,474.00,1319.4,9179.0
Multiplayer only,53.0,465.113208,698.484724,1.0,53.0,234.0,496.00,1176.8,3580.0
Other,6.0,1477.333333,2096.915226,6.0,95.0,440.0,2191.25,3965.0,5223.0
Single-player only,233.0,751.420601,2385.938721,1.0,19.0,134.0,519.00,1131.2,18568.0

tot

In [84]:
#  solo i tre gruppi principali
modes_interest = ["Single-player only", "Hybrid (SP+MP)", "Multiplayer only"]

df_b2_clean = df_b2[df_b2["game_mode"].isin(modes_interest)]

summary_b2 = (
    df_b2_clean
    .groupby("game_mode")
    .agg(
        total_games=("appid", "count"),

        # disponibilità dati
        games_with_playtime_forever=("average_playtime_forever", lambda x: (x > 0).sum()),
        games_with_playtime_2weeks=("average_playtime_2weeks", lambda x: (x > 0).sum()),

        # playtime (solo dove disponibile)
        median_playtime_forever=("average_playtime_forever", lambda x: x[x > 0].median()),
        median_playtime_2weeks=("average_playtime_2weeks", lambda x: x[x > 0].median()),
    )
)

#  percentuali di disponibilità
summary_b2["pct_with_playtime_forever"] = (
    summary_b2["games_with_playtime_forever"] / summary_b2["total_games"]
)

summary_b2["pct_with_playtime_2weeks"] = (
    summary_b2["games_with_playtime_2weeks"] / summary_b2["total_games"]
)

summary_b2

,total_games,games_with_playtime_forever,games_with_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,pct_with_playtime_forever,pct_with_playtime_2weeks
game_mode,,,,,,,
Hybrid (SP+MP),1587,948,253,603.0,167.0,0.597353,0.159420
Multiplayer only,409,228,53,344.0,234.0,0.557457,0.129584
Single-player only,2598,1506,233,333.5,134.0,0.579677,0.089684

## GRAFICI

GRAFICO 1

In [85]:
import pandas as pd


if "is_free" not in df_s2.columns:
    df_s2 = df_s2.copy()
    df_s2["is_free"] = df_s2["price"].eq(0)

# Calcolo quota free-to-play PER ANNO
yearly = (
    df_s2.groupby("release_year")
    .agg(
        total_games=("appid", "count"),
        free_games=("is_free", "sum")
    )
    .reset_index()
    .rename(columns={"release_year": "Year"})
)

yearly["Free-to-play share (%)"] = (
    yearly["free_games"] / yearly["total_games"] * 100
).round(2)

# Teniamo SOLO le due colonne richieste + filtro anni
cover_timeline = (
    yearly[
        (yearly["Year"] >= 2006) & (yearly["Year"] <= 2024)
    ][["Year", "Free-to-play share (%)"]]
    .sort_values("Year")
)

cover_timeline

    Year  Free-to-play share (%)
7   2006                    0.00
8   2007                   12.50
9   2008                   14.29
10  2009                    4.76
11  2010                    9.15
12  2011                    9.43
13  2012                   10.68
14  2013                    9.78
15  2014                    8.20
16  2015                   11.19
17  2016                   14.23
18  2017                   15.12
19  2018                   15.92
20  2019                   15.21
21  2020                   16.26
22  2021                   15.10
23  2022                   17.15
24  2023                   16.62
25  2024                   17.26

In [86]:
out_path = "/content/drive/MyDrive/DV_videogames/cover_timeline_f2p_share_2006_2024.csv"
cover_timeline.to_csv(out_path, index=False)
print("Saved:", out_path)

Saved: /content/drive/MyDrive/DV_videogames/cover_timeline_f2p_share_2006_2024.csv